kamp-us/monorepo

src/index.css
src/index.tsx
src/ui-library/globalStyles.ts

Signed-off-by: usirin <umutsirin1@gmail.com>

Use inter font

---

src/features/comment/Comment.tsx
src/routes/index.tsx
src/routes/send.tsx

fixes rendering "kaydediliyor" for every submit button

fix submit button text

---

src/routes/__auth/login.tsx

#27 
https://user-images.githubusercontent.com/88425310/168460020-e09dff40-7635-4b49-a4ca-5b3820819159.mov
t

fix: Error message appears even if the login page has more than 6 characters

---

src/routes/settings.tsx

Fix settings page auth problems

---

src/stitches.config.ts
src/ui-library/topnav/Topnav.tsx

Fixes the padding problem for mobile web

Give padding from sides to Topnav

---

src/routes/settings.tsx
tsconfig.json

Use authenticated amplify auth user for updating password

---

src/ui-library/Toast.tsx

Add Toast component

---

src/root.tsx
src/routes/posts/$id.tsx

add: Meta tags for base routes

---

src/routes/send.tsx

Issues #75 
https://user-images.githubusercontent.com/88425310/192132578-55e19306-c577-488b-a26b-268595128c0f.mov

add(Send): Post form validation

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

If we decide to approve this PR, these labels should be added to the issue labels:
- Status: Needs Triage
- Type: New Feature
- Status: Discussion
cc: @usirin

Introduce issue templates and pull request template

---

src/ui-library/Textarea.tsx

fix: Top Navbar stays below text area

---

src/routes/posts/$id.tsx

This pull request contains the solution to the issue mentioned in #87.

Fixes on css and error handling

---

src/routes/send.tsx
src/utils/index.ts

Added validation that checks the URL address when creating a post.

Added valid URL validation

---

src/routes/posts/$id.tsx

After posting a comment, the comment remains in the textarea #98 Fixed
Co-Authored-By: Rasit <12167194+rasitxy@users.noreply.github.com>
@usirin  @cansirin

Textarea bug fix

---

Dockerfile.dev
package.json

Updates the dev docker file to use `npm install` instead of `npm ci` so it doesn't reinstall everytime we run the container.
also adds a step to generate prisma

Update dev install command

---

src/routes/posts/$slug-$id.tsx

Author and Description meta tags for sharing

---

package-lock.json
package.json
src/ui-library/Dropdown.tsx
src/ui-library/MoreOptionsDropdown.tsx
src/ui-library/SocialMediaButtons.tsx
src/utils/index.ts

This PR implements #103 
More platform can be added if it's necessary.

Make posts sharable

---

src/features/comment/Comment.tsx
src/routes/posts/$slug-$id.tsx

expand comments if hash exists

---

Dockerfile.dev
docker-compose.yaml
package-lock.json
package.json

- Update several npm scripts to keep my sanity 😄 
- Include a ssl-proxy for being able to call the service with https

Docker fixes

---

src/root.tsx
src/ui-library/Toast.tsx

This PR handles proper Toast rendering

fix toast provider

---

.gitignore
apps/pano/docker-compose.yaml

This PR fixes docker-compose and gitignore files after monorepo changes

docker-compose & gitignore fix

---

.gitignore
.lintstagedrc.json
apps/pano/src/utils/index.ts
package-lock.json

This PR fixes husky command for turbo and adds .turbo to .gitignore file.
index.ts is changed because husky, it was going to generated every run for everybody so I just wanted to push it with this PR. 
After doing npm install in the root folder, it added name of our app to the package-lock.json file

husky & turbo fix

---

apps/pano/package.json
apps/pano/src/routes/api/parse-meta.ts
apps/pano/src/routes/send.tsx
apps/pano/src/utils/index.ts
package-lock.json

This PR implements #105. 
https://user-images.githubusercontent.com/8138047/201501121-5ae0ed45-1570-489c-95b7-f3061f4371aa.mov

parse title from url meta tags

---

apps/pano/src/features/comment/Comment.tsx
apps/pano/src/routes/posts/$slug-$id.tsx

This PR fixes #119. It also places error messages right next to the action button.

fix comment error positions

---

apps/pano/prisma/migrations/20221113042836_make_comments_upvotable/migration.sql
apps/pano/prisma/schema.prisma
apps/pano/src/features/comment/Comment.tsx
apps/pano/src/models/comment.server.ts
apps/pano/src/models/post.server.ts
apps/pano/src/routes/commentUpvote.tsx
apps/pano/src/ui-library/Text.tsx
apps/pano/src/ui-library/UpvoteButton.tsx

Make comments upvotable

---

apps/pano/.eslintrc.js
apps/pano/package.json
apps/pano/tsconfig.json
package-lock.json
packages/kampus-eslint-config/.gitignore
packages/kampus-eslint-config/index.cjs
packages/kampus-eslint-config/package.json
packages/kampus-eslint-config/remix.cjs
packages/kampus-tsconfig/base.json
packages/kampus-tsconfig/package.json
packages/kampus-tsconfig/remix.json

Creates 2 packages:
- `@kampus/tsconfig`: to be shared between all packages
- `@kampus/eslint-config`: to be shared between all packages, exposes different config for remix apps
```js
// apps/random-app/.eslintrc.js
module.exports = {
extends: ["@kampus/eslint-config", "@kampus/eslint-config/remix"]
}
```
Fixes #136

Tooling packages

---

.lintstagedrc.json
apps/pano/src/routes/api/auth/login.ts
apps/pano/src/routes/api/auth/logout.ts
apps/pano/src/routes/api/auth/register.ts
apps/pano/src/routes/api/parse-meta.ts
apps/pano/src/routes/index.tsx
apps/pano/src/routes/posts/$id.edit.tsx
apps/pano/src/routes/search.tsx
apps/pano/src/routes/send.tsx
apps/pano/src/routes/settings.tsx
apps/pano/src/routes/site/$.tsx
apps/pano/src/ui-library/Dropdown.tsx
apps/pano/src/ui-library/MoreOptionsDropdown.tsx
apps/pano/src/utils/index.ts
turbo.json

Run eslint on repo, and do changes to make sure it runs.

Run eslint

---

.husky/pre-commit
.lintstagedrc.json
package-lock.json
package.json

Remove pre-commit hooks to increase velocity

---

apps/pano/prisma/migrations/20221116084646_add_post_content/migration.sql
apps/pano/prisma/schema.prisma
apps/pano/src/features/post/PostItem.tsx
apps/pano/src/features/post/PostList.tsx
apps/pano/src/models/post.server.ts
apps/pano/src/routes/posts/$id.edit.tsx
apps/pano/src/routes/posts/$slug-$id.tsx
apps/pano/src/routes/send.tsx
apps/pano/src/utils/index.ts
package-lock.json

This PR introduces "content" field for Post model. From now on, content and site is optional fields for Post but Post is required to have at least URL or content.
Fixes #153 Implements #140
Post:
Send post:
Edit post:

Add post content

---

apps/pano/src/features/comment/Comment.tsx
apps/pano/src/routes/posts/$slug-$id.tsx

This PR updates content validation for post & comment creation.

Comment errors

---

apps/pano/src/features/comment/Comment.tsx
apps/pano/src/features/post/PostItem.tsx

Comment & Post content whitespace

---

apps/pano/prisma/seed.ts
apps/pano/src/features/post/MoreOptionsDropdown.tsx
apps/pano/src/features/post/PostItem.tsx

fixes #154
Post item used to check if user was able to edit the post to show the dropdown. I removed it.
A check for userCanEdit already exists in dropdown, fixed some UI.
There's also a commit on prisma seed that can make multiple users.

Dropdown visibility

---

apps/pano/src/models/post.server.ts

fixes #174
Added content search for posts. Posts without links work already.

Update search to include all posts

---

packages/kampus-ui/package.json

fix kampus ui wrong build command

kampus ui script fix

---

apps/pano/src/features/comment/Comment.tsx
apps/pano/src/features/comment/MoreOptionsDropdown.tsx
apps/pano/src/utils/index.ts

Comment share

---

apps/pano/src/root.tsx
apps/pano/src/routes/posts/$slug-$id.tsx

Image meta tags and og tags added

---

apps/pano/src/features/comment/Comment.tsx

fixes #195 
doesn't seem to effect anything when we change it

use useEffect instead of useLayoutEffect

---

apps/pano/src/features/comment/Comment.tsx
apps/pano/src/features/comment/CommentDeleteAlert.tsx
apps/pano/src/features/comment/EditCommentForm.tsx
apps/pano/src/features/comment/MoreOptionsDropdown.tsx
apps/pano/src/models/comment.server.ts
apps/pano/src/models/post.server.ts
apps/pano/src/routes/commentEdit.tsx
apps/pano/src/routes/delete-comment.ts

Fixes #175
Not sure about comment edit...
#EDIT
--------
#DELETE

Comment Edit & Comment Delete

---

apps/pano/src/features/comment/Comment.tsx

fixes #197 
When submitting is done, expand comments.

expand subcomments when commenting a comment

---

apps/pano/src/models/post.server.ts

fixes #204 
This pr sorts comments by their createdAts descendantly(newest first) at the database query.

feat(pano): sort comments by createdAt

---

.github/workflows/ci.yml
.github/workflows/pano-deploy.yml
apps/pano/Dockerfile
apps/pano/Dockerfile.dev
apps/pano/docker-compose.yaml
apps/pano/fly.toml
apps/pano/package.json
package-lock.json
package.json

ops(@kampus-apps/pano): add fly.io deployment

---

turbo.json

This PR fixes docker and turbo problem with the current development. 
The problem was not having used scripts commands as development task in turbo.json. I also cleared unused commands since we don't have them in package.json.

fix development tasks for turbo

---

apps/pano/package.json
apps/pano/src/db.server.ts
apps/pano/src/session.server.ts
apps/pano/src/utils/env.server.ts
package-lock.json

safe environment variables

---

apps/pano/src/routes/send.tsx

Fixes #105
This PR adds meta tags parsing process to focus on leave action.

fix(@kampus-apps/pano): add parsing on focus leave

---

.github/workflows/ci.yml

removing npm cache to see if it's gonna help us for github actions

ci(repo): remove npm cache for now

---

apps/pano/prisma/seed.ts

added posts and comment contents for random users
Closes #231

add comment contents

---

apps/pano/src/utils/index.ts

getExternalPostURL changes

---

apps/pano/Dockerfile
apps/pano/package.json

ci(@kampus-apps/pano): use raw npm scripts in docker file

---

apps/pano/src/routes/posts/$id.edit.tsx
apps/pano/src/routes/posts/$slug.$id.tsx
apps/pano/src/routes/send.tsx

fix textarea resize bug and some typo

---

apps/pano/app/routes/__auth/login.tsx

#258 
Fixed login button,
- Although I mentioned about _post a comment_ also have redundant gap and padding, I actually saw that it need the gap for validation message, and paddings are fine.

fix: 5px gap between login button at the top

---

apps/pano/app/features/post/PostItem.tsx
apps/pano/app/routes/send.tsx
apps/pano/app/utils/index.ts

closes: #228 
Co-Authored-By: Rasit 12167194+durmusrasit@users.noreply.github.com
Co-Authored-By: ikadgzl <ikadgzl@gmail.com>

add getPostSlugLink  and getPostSiteLink functions

---

apps/pano/app/utils/env.server.ts
apps/pano/package.json
package-lock.json

refactor: replace envsafe with znv

---

apps/pano/app/features/user-dropdown/UserDropdown.tsx

fix DropdownMenu button border

---

apps/pano/app/features/authenticator/strategies.ts
apps/pano/app/features/email/components/Registration.tsx
apps/pano/prisma/migrations/20230306011111_add_otp/migration.sql
apps/pano/prisma/schema.prisma
package-lock.json
package.json

Fixes #245 
This PR adds OTP auth strategy for remix-auth

feat: Add otp auth strategy

---

apps/pano/app/authenticator.server.ts
apps/pano/app/features/authenticator/KampusAuthenticator.ts
apps/pano/app/features/authenticator/index.ts
apps/pano/app/features/topnav/Topnav.tsx
apps/pano/app/models/user.server.ts
apps/pano/app/root.tsx
apps/pano/app/routes/__auth/login-form.tsx
apps/pano/app/routes/__auth/login.tsx
apps/pano/app/routes/__auth/magic-link.tsx
apps/pano/app/routes/api/auth/login.ts
apps/pano/app/routes/api/auth/logout.ts
apps/pano/app/routes/api/auth/otp.tsx
apps/pano/app/routes/change-theme.tsx
apps/pano/app/routes/posts/$id.edit.tsx
apps/pano/app/routes/posts/$slug.$id.tsx
apps/pano/app/routes/send.tsx
apps/pano/app/routes/settings.tsx
apps/pano/app/session.server.ts

fixes #274
- Now we use one time password login at: `/login`
- Login with password is at: `/login-form`

feat(@kampus-apps/pano): start using authenticator

---

packages/kampus-ui/src/layout-components/Button.tsx

fix cevapla button cursor pointer

---

apps/pano/app/routes/api/auth/logout.ts

fix: the login page cannot be reached because of previous cookies

---

apps/pano/app/features/post/PostItem.tsx

fix(@kampus-apps/pano): add | as a separator

---

apps/pano/app/features/analytics/gtag.client.ts
apps/pano/app/root.tsx
apps/pano/app/utils/env.server.ts

closes #290 
This PR introduces google analytics for page view events happening in the pano.

feat(@kampus-apps/pano): integrate google analytics

---

apps/pano/.env.example
apps/pano/app/features/comment/Comment.tsx
apps/pano/app/features/comment/MoreOptionsDropdown.tsx
apps/pano/app/features/config/config-context.tsx
apps/pano/app/features/post/MoreOptionsDropdown.tsx
apps/pano/app/features/post/PostItem.tsx
apps/pano/app/root.tsx
apps/pano/app/routes/posts/$slug.$id.tsx
apps/pano/app/utils/env.server.ts
apps/pano/app/utils/index.ts

fix(@kampus-apps/pano): fix comment share url

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md

chore(repo): update github issue & pr templates

---

apps/pano/app/features/authenticator/strategies.ts
apps/pano/prisma/migrations/20230313002142_add_social_provider/migration.sql
apps/pano/prisma/schema.prisma

feat: Social identity integration for existing users, disallow user creation from oauth provider logins

---

apps/pano/app/features/oauth/OAuthLoginForm.tsx
apps/pano/app/routes/__auth/login.tsx
packages/kampus-ui/src/OAuthProviderLogo.tsx
packages/kampus-ui/src/index.tsx

Exported OAuth login form into a dynamic React component and created a dynamic provider logo component which is being used by the login form.
Tested manually.

feat: Dynamic OAuthLoginForm, OAuthProviderLogo components, and logo addition to login buttons

---

.github/workflows/graphql-deploy.yml
.github/workflows/pano-deploy.yml
services/graphql/.dockerignore
services/graphql/Dockerfile
services/graphql/cmd/graphql/main.go
services/graphql/docker-compose.yaml
services/graphql/fly.toml

This PR adds changes for deploying graphql service with a trivial schema. We are getting this ready so we can start development for our twirp services.
- navigate to `services/graphql`
- run `docker-compose up --build` & keep it running
- open another terminal window and run the following:
```
curl -XPOST -d {"query": "{ hello }"} localhost:8021/graphql
```
- confirm that you have the following response:
```
{"data":{"hello":"Hello, world!"}}% 
```

ci(repo): Deploy GraphQL service

---

apps/pano/app/routes/settings.tsx

1. Sign in.
2. Go settings page.
3. Verify spelling of labels and button text.

refactor: change spelling of Turkish words

---

services/graphql/clients/clients.go
services/graphql/cmd/graphql/main.go
services/graphql/docker-compose.yaml
services/graphql/fly.toml
services/graphql/resolver/post_query.go
services/graphql/resolver/post_resolver.go
services/graphql/resolver/resolver.go
services/pano-api/fly.toml

ONE OF THE BIGGEST MILESTONES
GQL WILL HAVE PANO NOW
ONE MORE STEP CLOSER

feat(services/graphql): connect pano api

---

services/graphql/fly.toml

fix(services/pano-api): fix typo at fly.toml

---

services/pano-api/internal/backend/backend.go
services/pano-api/internal/backend/postgresql/postgresql.go
services/pano-api/internal/models/args.go
services/pano-api/server/get_posts.go

Graphql query
```
{
pano{
posts(input: {first: 10}){
edges{
cursor
}
}
}
}
```

feat(services/pano-api): add limit and offset to posts query

---

apps/pano/app/features/comment/Comment.tsx
apps/pano/app/features/post/PostItem.tsx
apps/pano/app/features/upvote/UpvoteButton.tsx
apps/pano/app/routes/commentUpvote.tsx
apps/pano/app/routes/upvote.tsx

Upvote buttons require the user to be logged in, if user is not logged in, instead of disabling the buttons redirect them to login page.
Manually, by hand. ☹️

feat: Upvotes redirect to login page

---

apps/pano/app/models/post.server.ts

Searched `hacker` to find `Hacker News` title:
Reference:
[Prisma Documentation](https://www.prisma.io/docs/concepts/components/prisma-client/case-sensitivity#options-for-case-insensitive-filtering)

feat: Make search case insensitive

---

services/README.md

feat: add service architecture diagram

---

apps/pano/app/features/oauth/OAuthLoginForm.tsx
apps/pano/app/routes/__auth/login.tsx
packages/kampus-ui/src/stitches.config.ts

tested with chrome developer tools

Added breakpoint to stiches and made login page buttons responsive

---

package-lock.json
package.json

add new workspaces, also fix an critical dependency problem

chore(repo): add new workspaces: protos, services

---

apps/pano/Dockerfile
apps/pano/package.json

fix(apps/pano): update dockerfile to not do prisma things

---

apps/gql/env.ts

fix(apps/gql): workflow build error

---

package-lock.json
packages/ui/components/dialog.tsx
packages/ui/components/dropdown-menu.tsx
packages/ui/components/input.tsx
packages/ui/components/label.tsx
packages/ui/components/select.tsx
packages/ui/components/separator.tsx
packages/ui/components/textarea.tsx
packages/ui/components/toast.tsx
packages/ui/components/use-toast.ts
packages/ui/package.json

Hello,
This PR adds components compatible with `Kampus-UI` to our newly created library, `ui-next` These changes will allow us to utilize the features of `Kampus-UI` in the `ui-next` project, ensuring consistency throughout the development process.
The changes I have made include the following components:
- dialog
- dropdown-menu
- input
- label
- select
- separator
- textarea
- toast
Please review and provide feedback. Thank you!

feat(@kampus/ui): Adding components compatible with Kampus-UI

---

.eslintrc.js
apps/kampus/.eslintrc.json
packages/kampus-eslint-config/next.js

This should fix the eslint error we see in vercel.

ci(@kampus/eslint-config): remove problematic ts eslint config

---

apps/gql/.env.example
apps/gql/loaders/index.ts
apps/gql/loaders/sozluk.ts
apps/gql/loaders/types.ts
apps/gql/next.config.mjs
apps/gql/package.json
apps/gql/schema/resolvers/Query/SozlukQuery/term.ts
apps/gql/schema/resolvers/Query/index.ts
apps/gql/schema/resolvers/index.ts
apps/gql/schema/schema.graphql
apps/gql/schema/types.generated.ts
apps/kampus/.env.example
apps/kampus/app/sozluk/[term]/layout.tsx
apps/kampus/app/sozluk/[term]/page.tsx
apps/kampus/env.ts
apps/kampus/package.json
package-lock.json
packages/sozluk-content/.gitignore
packages/sozluk-content/contentlayer.config.ts
packages/sozluk-content/index.ts
packages/sozluk-content/package.json
packages/sozluk-content/terms/deployment.mdx
packages/sozluk-content/terms/rps.mdx
packages/sozluk-content/tsconfig.json
turbo.json

- add `@kampus/sozluk-contents`
- add `sozluk loaders` for `@kampus-apps/gql`
- add `sozluk.kamp.us/[term]` support

Sozluk contents

---

db/pano-prisma/fly.toml

add fly.toml file to have fly configuration on file.

ci(@kampus-db/pano-prisma): add fly.toml

---

apps/ui/.storybook/main.ts
apps/ui/.storybook/preview.ts
apps/ui/package.json
apps/ui/postcss.config.js
apps/ui/stories/Avatar.stories.tsx
apps/ui/stories/Button.stories.ts
apps/ui/stories/Input.stories.tsx
apps/ui/styles.css
apps/ui/tailwind.config.js
db/pano-prisma/fly.toml
package-lock.json
package.json
packages/sozluk-content/terms/mvp.mdx
packages/sozluk-content/terms/senchabot.mdx

dev -> main

---

packages/sozluk-content/terms/continuous-deployment.mdx
packages/sozluk-content/terms/continuous-integration.mdx
packages/sozluk-content/terms/deployment.mdx
packages/sozluk-content/terms/quality-assurance.mdx
packages/sozluk-content/terms/stlc.mdx

Add new sozluk terms

---

packages/sozluk-content/terms/continuous-deployment.mdx

Fix typo in CD term

---

README.md

Main readme is adjusted to match current setup. If any information is wrong please let me know.
Read through Readme.md
Re-opened from :https://github.com/kamp-us/monorepo/pull/443

feat: Readme adjusted for packages

---

apps/ui/stories/AlertDialog.stories.tsx
apps/ui/stories/Avatar.stories.tsx
apps/ui/stories/Button.stories.tsx
apps/ui/stories/Input.stories.tsx
apps/ui/tsconfig.json

this pr fixes eslint errors and adds tsconfig for `@kampus-apps/ui` app

chore(@kampus-apps/ui): use satisfies operator

---

packages/tailwind/defaultTheme.ts
packages/tailwind/index.ts
packages/tailwind/plugin.ts

nothing important, i made this thinking that i will use the tailwind theme in #456, but i ended up using the preset instead. But still wanted to keep this as this cleans up the code pretty nicely, and also exported it at package level in case we want to use it somewhere else.

feat(@kampus/tailwind): create defaultTheme

---

apps/gql/package.json
apps/kampus/package.json
deprecated/pano/package.json
package-lock.json
package.json
packages/ui/package.json

Updated all inertial package versions to * according to #466.
Windows 11
With : 
"npm install", 
"npx turbo build",
"npx turbo dev"

fix(repo): update package.json dependencies

---

apps/kampus/app/postaci/send/route.ts
apps/kampus/env.ts
apps/kampus/package.json
package-lock.json
packages/email/.gitignore
packages/email/client.ts
packages/email/components/Email.tsx
packages/email/emails/MagicLink.tsx
packages/email/emails/index.ts
packages/email/handlers/resend.ts
packages/email/index.ts
packages/email/package.json
packages/email/render.ts
packages/email/schemas.ts
packages/email/tsconfig.json
turbo.json

Closes #456 
Closes #463 
Make a `POST` request to `/postaci/send` with following json payload:
```json
{
"email": {
"to": "kampus-test@resend.dev",
"subject": "TEST - kamp.us'e hoşgeldin"
},
"kampusEmail": {
"type": "magic-link",
"props": {
"url": "https://pasaport.kamp.us"
}
}
}
```

feat: add @kampus/email

---

apps/gql/package.json
apps/kampus/package.json
apps/ui/package.json
config/eslint/package.json
db/pano-prisma/package.json
package-lock.json
packages/email/package.json
packages/relay/package.json
packages/sozluk-content/package.json
packages/tailwind/package.json
packages/ui/package.json

Add volta everywhere

---

apps/kampus/middleware.ts

feat(@kampus/kampus): add middleware.ts for enable cors

---

package-lock.json
package.json

Update `turbo` package dependency.

upgrade turborepo

---

packages/sozluk-content/terms/happy-path.mdx

New sozluk term: happy-path

---

.github/ISSUE_TEMPLATE/new_epic.yml

Adds a new issue template to create epics.

chore: create a github issue template for epics

---

package-lock.json
packages/sozluk-content/package.json
packages/sozluk-content/turbo/generators/config.ts
packages/sozluk-content/turbo/generators/templates/sozluk-term.hbs

Added `@turbo/gen` in order to generate Sozluk terms.
How to use:
1- go to `packages/sozluk-content`
2- run `turbo gen sozluk-term`
3- answer prompts (title, tags, content)
4- you will see created term in the `terms` folder

feat(@kampus/sozluk-content): Add term generator
