- Dockerfile.dev
- docker-compose.yaml
change ENTRYPOINT to CMD, because ENTRYPOINT is preferred when you want to define an executable
change link to networks, because "  The --link flag is a deprecated, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link."
docker-compose, app service, the build step has been fixed
> Dockerfile and  Docker-compose Fix

- apps/pano/README.md
The readme for pano details the default admin password to be `123123123` when it was recently updated to `123123`. This changes the readme with the updated one so new contributors don't get confused.
> Update readme password

- packages/kampus-ui/package.json
fixes #165 
I changed package versions for kampus-ui so that they use a fixed version. Since those packages are "dependant?" from eachother, version differences can and do effect functionality, which is sad... 
For more, on this issue [radix-ui](https://github.com/radix-ui/primitives), see : 
- https://github.com/radix-ui/primitives/issues/1088
- https://github.com/radix-ui/primitives/issues/1241#issuecomment-1228956377
> fixed package versions for kampus-ui

- apps/pano/docker-compose.yaml
fixes #184 
Remix uses a websocket for development server, in our configs it uses the port 8002. So adding this port to the docker compose makes auto reload work for macOS and windows.
For windows, a WSL extension is needed and the repository files must be in WSL filesystem. In /home/username or /root.
The extension crates a vscode server in WSL and connects your VSCode into this server.
You can also click here to initiate the connexion manually, if not setup, it should setup the server automatically.
> auto reload for macos and windows

- apps/pano/src/features/comment/Comment.tsx
fixes #196 
Closes comment when it tries to reset the form once submitting finished. Tried on slow internet mode, it works as expected.
> close comment comment textarea after submitting

- apps/pano/src/features/post/MoreOptionsDropdown.tsx
- apps/pano/src/features/post/PostItem.tsx
- apps/pano/src/features/post/PostList.tsx
- apps/pano/src/models/post.server.ts
- apps/pano/src/routes/index.tsx
- apps/pano/src/routes/posts/$id.edit.tsx
- apps/pano/src/routes/posts/$slug-$id.tsx
- apps/pano/src/routes/search.tsx
- apps/pano/src/routes/site/$.tsx
- apps/pano/src/utils/index.ts
PostWithCommentCount type defined. DB queries are updated with PostWithCommentCount type requirements. Post references were replaced with the PostWithCommentCount type.
getAllPosts(Posts page), getPostById(Post edit page), getPostsBySite(Posts with specified site name), searchPosts(Posts with search) queries optimized. 
Fixes #193 
<details><summary>Screenshots</summary>
Content:
DB response:
Content:
DB response:
</details>
> Refine data requests

- apps/pano/src/features/post/PostItem.tsx
- packages/kampus-ui/src/InternalLink.tsx
- packages/kampus-ui/src/index.tsx
An InternalLink component has been created and added to the Kampus/UI package. The package's index file has been updated to include the new component.
The InternalLink component is similar to the ExternalLink component, but it only redirects users to locations within the same website or application.
Fixes #190 
<details><summary>Screenshots</summary>
</details>
> Title without URL

- apps/pano/src/features/post/PostItem.tsx
- packages/kampus-ui/src/InternalLink.tsx
- packages/kampus-ui/src/index.tsx
An InternalLink component has been created and added to the `@kampus/ui` package. The package's index file has been updated to include the new component.
The InternalLink component is similar to the ExternalLink component, but it only redirects users to locations within the same website or application.
Fixes #190 
<details><summary>Screenshots</summary>
</details>
When submitting a PR, please also <ins>**create an issue**</ins> documenting the error and [manually link to an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-or-branch-to-an-issue-using-the-issue-sidebar) or mention it in the description using #<issue_id>.
> Title without URL (#217)

- apps/pano/src/features/comment/Comment.tsx
- apps/pano/src/features/post/PostItem.tsx
- apps/pano/src/features/post/PostSortFilters.tsx
- apps/pano/src/models/post.server.ts
- apps/pano/src/routes/index.tsx
- apps/pano/src/routes/posts/__filters.tsx
- apps/pano/src/routes/posts/__filters/active.tsx
- apps/pano/src/routes/posts/__filters/hot.tsx
- apps/pano/src/routes/posts/__filters/liked.tsx
Closes #71 
This pull request adds the following functionality:
- 3 new routes under the post route, hot, active, and liked
- A new PostSorter component
- Sorting operations
- I was going to introduce another `<Outlet />` for these routes in order to have only one `<PostSorter />` component. When I create an index route for posts and have outlet for these routes, it affects other pages such as "$slug-$id" route which is not what we want. For that reason, I had to render `<PostSorter />` at each route. Since PostSorter acts accordingly to url, there shouldn't be a state problem but I would like to hear your suggestions and come up with a better solution.
- PostSorter component's placement & styling
> Sort posts

- apps/pano/app/features/authenticator/KampusAuthenticator.ts
- apps/pano/app/features/authenticator/index.ts
- apps/pano/app/features/authenticator/strategies.ts
- apps/pano/app/models/user.server.ts
- apps/pano/app/session.server.ts
- apps/pano/package.json
- package-lock.json
We introduce our own `KampusAuthenticator` to make sure `authenticator.authenticate` call is type safe, and autocompletes with the strategies we register when we are creating an instance.
Fixes #241
> feat(@kampus-apps/pano): add remix-auth and remix-auth-form strategy

- apps/pano/app/features/auth/user-context.tsx
- apps/pano/app/features/authenticator/index.ts
- apps/pano/app/features/comment/Comment.tsx
- apps/pano/app/features/comment/MoreOptionsDropdown.tsx
- apps/pano/app/features/post/MoreOptionsDropdown.tsx
- apps/pano/app/features/post/PostItem.tsx
- apps/pano/app/features/post/PostList.tsx
- apps/pano/app/features/topnav/Topnav.tsx
- apps/pano/app/models/user.server.ts
- apps/pano/app/routes/change-theme.tsx
- apps/pano/app/routes/posts/$id.edit.tsx
- apps/pano/app/routes/send.tsx
- apps/pano/app/session.server.ts
I've scanned through all the files in the repo in order to fix some import and type issues such as:
-  wrong imports,
-  redundant imports,
-  incorrectly ordered types.
Created a new type in `user.model` to use it in `change-theme` where `updateTheme()` function requires `Theme` parameter, without it causes error.
Finally, I've created two new FIXME's, I don't know if those are deliberately existing, but I just wanted to point out.
> refactor: type and import problems

- apps/pano/package.json
- package-lock.json
- package.json
`remix-auth-otp` package was installed on the main folder so this is giving errors. This should be installed on pano.
> fix(@kampus-apps/pano): add otp to pano package.json

- apps/pano/app/features/post/PostItem.tsx
> refactor: show created for posts

- apps/pano/app/routes/__auth/login.tsx
This Pull Request fixes the width of the SmallLink for "Şifreyle giriş yapmak için tıkla" in the login page. The link will now only be clickable when hovering over it and will not cover the entire page width.
- [  ] discord username: `username#0001`
1. Go to the login page.
2. Note that the SmallLink for "Şifreyle giriş yapmak için tıkla" no longer covers the entire page width.
3. Confirm that the link is clickable only when hovering over it.
https://user-images.githubusercontent.com/88425310/224707344-5c9d5da4-59a5-446e-884a-dfd269fb981a.mov
> fix: login page SmallLink covers the whole page

- packages/kampus-ui/src/Input.tsx
Fixes unexpected background color change in select areas when using AutoFill feature. This change may cause confusion for users and negatively affect the overall user experience. With this PR, it is ensured that the select areas retain their original background color.
- [ x ] Closes #325 
- [ x ] PR must be created for an issue from issues under "In progress" column from [our project board](https://github.com/orgs/kamp-us/projects/2/views/1).
- [ x ] A descriptive and understandable title: The PR title should clearly describe the nature and purpose of the changes. The PR title should be the first thing displayed when the PR is opened. And it should follow the semantic commit rules, and should include the app/package/service name in the title. For example, a title like …
> fix: background color issue in AutoFill select fields

- apps/pano/app/features/comment/EditCommentForm.tsx
The problem that there is no space between the textarea and the buttons when using the Firefox browser has been resolved, and a space is left between the two buttons.
1. sign in
2. Press the edit button of a comment you have written
3. Verify that there is a space between the textarea and the buttons
4. Verify that there is a space between the buttons (Save, cancel)
safari: 
Google Chorme: 
Brave: 
Firefox:
> refactor: add spacing to buttons for comment edit

- apps/pano/app/features/comment/CommentDeleteAlert.tsx
- apps/pano/app/features/post/PostDeleteAlert.tsx
This PR updates the variant of 'CommentDeleteAlert' and 'PostDeleteAlert' buttons to gray
1. sign in
2. Press the button to delete a post you have written
3. Check that the 'hayır' button is in the gray variant
current behavior:
> refactor: change alert modal buttons

- apps/pano/app/features/comment/Comment.tsx
- apps/pano/app/features/notification-dropdown/NotificationDropdown.tsx
- apps/pano/app/features/topnav/Topnav.tsx
- apps/pano/app/models/notification.server.ts
- apps/pano/app/routes/commentUpvote.tsx
- apps/pano/app/routes/notifications/my-notifications.tsx
- apps/pano/app/routes/notifications/my-notifications/$id.tsx
- apps/pano/app/routes/posts/$slug.$id.tsx
- apps/pano/app/routes/upvote.tsx
- apps/pano/prisma/migrations/20230406151334_add_notifications/migration.sql
- apps/pano/prisma/migrations/20230406152607_add_read_status/migration.sql
- apps/pano/prisma/migrations/20230406155043_update_notification_types/migration.sql
- apps/pano/prisma/migrations/20230407202239_add_notification_url/migration.sql
- apps/pano/prisma/schema.prisma
- apps/pano/prisma/seed.ts
- package-lock.json
First iteration of the notification service for Pano, could be improved in further iterations.
- User gets a notification for an event (such as comment/upvote), on a post/comment that they own.
- An unread identifier will appear on top-right of the notifications icon if there are unread notifications.
- Notifications could be marked as read by clicking on them or clicking on "Hepsini okundu olarak işaretle" button.
- Unread identifier will disappear if all notifications are marked as read.
- "Upvote on comment": When user gets an upvote on their comment, they will get a notification linking to the comment which got upvoted alongside the username who upvoted the comment.
- "Upvote on post": When user gets an upvote on their post, they will get a notification linking to the post which got …
> feat(apps/pano): Notification service

- apps/pano/app/root.tsx
Added an initial theme property to theme provider, which will set the theme initially to the user's preference and not "DARK".
The problem only exists on published version at pano-dev.kamp.us. Yet in local builds, there was an initial render with "DARK" theme selected, which gets updated afterwards. I believe this re-render is not being triggered on pano-dev.kamp.us, since this PR solves our initial dark mode render problem, I believe it solves the refresh problem as well.
> fix(apps/pano): light theme preference not retained after page refresh

- apps/pano/package.json
npm start was not able to set NODE_ENV environment variable in windows systems, since the command was not right. Added cross-env prefix to make sure it runs on Windows computers
Tested manually
> fix(apps/pano): npm start does not run properly on windows computers

- apps/kampus/next.config.mjs
maps pano.kamp.us -> kamp.us/pano so that we can use one next application for all products.
> ci(@kampus/kampus): add rewrite config

- package-lock.json
- package.json
updated the turbo version, we needed to do this anyway. but the weird thing is that it added turbo package resolutions back to the package-lock, which is why the builds were failing. interesting.
> ci(repo): update turbo version

- apps/ui/package.json
build-storybook script renamed to build because vercel/turbo will trigger "build" named script
> ci(apps/ui): fix app build

- .github/workflows/ci.yml
builds are failing because next apps require env vars to be present on build time.
> ci: update ci.yml with fake env vars
